name: final_project
description: "Final_flutter_project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Floor ORM
  floor: ^1.4.0
  floor_annotation: ^1.4.0
  sqflite: ^2.0.0

  # other
  path_provider: ^2.0.11
  path: ^1.9.1
  cupertino_icons: ^1.0.8
  encrypted_shared_preferences: ^3.0.1
  provider: ^6.0.5
  intl: ^0.19.0
  video_player: ^2.7.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Floor code generator
  floor_generator: ^1.4.0
  build_runner: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/dark_plane.png
    - assets/images/reservation.png
    - assets/images/customers.png
    - assets/images/flight.png
    - assets/images/airplanes.png
    - assets/videos/night_plane.mp4
